

spring:
  application:
    name: way-api
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
#    store-type: redis
    store-type: none
  # redis 配置
  redis:
    host: localhost
    port: 6379
    #    password: redispwd123
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-wait: 50000
        max-active: 8
  profiles:
    active: dev

server:
#  port: 7529
  port: 17529
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
way:
  api:
    access-key: a5f2534011dbcf8b0450fb1d263e4879
    secret-key: 959cf0d8ce0d3fa6a207b9e9a70aa891
#    user-id: 1
#    app-id: way
#    app-secret: 1

cn:
  wuaiyang:
    name: "way"
